import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const env = createEnv({
  server: {
    SUPABASE_SERVICE_ROLE_KEY: z.string().min(1, {
      message: "SUPABASE_SERVICE_ROLE_KEY is required. Get it from your Supabase project settings → API.",
    }),
    CAL_WEBHOOK_SECRET: z.string().optional(),
    MIROTALK_URL: z.string().url().optional(),
    MIROTALK_API_KEY: z.string().optional(),
    DAILY_API_KEY: z.string().optional(),
    DAILY_DOMAIN: z.string().optional(),
    RESEND_API_KEY: z.string().optional(),
    STRIPE_SECRET_KEY: z.string().optional(),
    STRIPE_PUBLISHABLE_KEY: z.string().optional(),
    STRIPE_WEBHOOK_SECRET: z.string().optional(),
    CHATWOOT_ACCOUNT_ID: z.string().optional(),
    CHATWOOT_API_TOKEN: z.string().optional(),
    CHATWOOT_BASE_URL: z.string().url().optional(),
    TYPEBOT_API_TOKEN: z.string().optional(),
    OPENROUTER_API_KEY: z.string().optional(),
    VAPID_PRIVATE_KEY: z.string().optional(),
    CRON_SECRET: z.string().min(16, {
      message: "CRON_SECRET is required (min 16 chars) to protect cron endpoints from unauthenticated triggers. Generate one with `openssl rand -hex 32`.",
    }),
    SENTRY_DSN: z.string().optional(),
    SENTRY_ORG: z.string().optional(),
    SENTRY_PROJECT: z.string().optional(),
    UPSTASH_REDIS_REST_URL: z.string().url().optional(),
    UPSTASH_REDIS_REST_TOKEN: z.string().optional(),
    THERAPIST_SECRET_KEY: z.string().optional(),
    TERMS_VERSION: z.string().optional(),
    NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  },
  client: {
    NEXT_PUBLIC_SUPABASE_URL: z.string().url({
      message: "NEXT_PUBLIC_SUPABASE_URL must be a valid URL. Get it from your Supabase project settings → API.",
    }),
    NEXT_PUBLIC_SUPABASE_ANON_KEY: z.string().min(1, {
      message: "NEXT_PUBLIC_SUPABASE_ANON_KEY is required. Get it from your Supabase project settings → API.",
    }),
    NEXT_PUBLIC_SITE_URL: z.string().url({
      message: "NEXT_PUBLIC_SITE_URL must be a valid URL (e.g., http://localhost:3000 or https://somove.app).",
    }),
    NEXT_PUBLIC_CHATWOOT_WEBSITE_TOKEN: z.string().optional(),
    NEXT_PUBLIC_CHATWOOT_BASE_URL: z.string().url().optional(),
    NEXT_PUBLIC_VAPID_PUBLIC_KEY: z.string().optional(),
  },
  runtimeEnv: {
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY,
    CAL_WEBHOOK_SECRET: process.env.CAL_WEBHOOK_SECRET,
    MIROTALK_URL: process.env.MIROTALK_URL,
    MIROTALK_API_KEY: process.env.MIROTALK_API_KEY,
    DAILY_API_KEY: process.env.DAILY_API_KEY,
    DAILY_DOMAIN: process.env.DAILY_DOMAIN,
    RESEND_API_KEY: process.env.RESEND_API_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    CHATWOOT_ACCOUNT_ID: process.env.CHATWOOT_ACCOUNT_ID,
    CHATWOOT_API_TOKEN: process.env.CHATWOOT_API_TOKEN,
    CHATWOOT_BASE_URL: process.env.CHATWOOT_BASE_URL,
    TYPEBOT_API_TOKEN: process.env.TYPEBOT_API_TOKEN,
    OPENROUTER_API_KEY: process.env.OPENROUTER_API_KEY,
    VAPID_PRIVATE_KEY: process.env.VAPID_PRIVATE_KEY,
    CRON_SECRET: process.env.CRON_SECRET,
    SENTRY_DSN: process.env.SENTRY_DSN,
    SENTRY_ORG: process.env.SENTRY_ORG,
    SENTRY_PROJECT: process.env.SENTRY_PROJECT,
    UPSTASH_REDIS_REST_URL: process.env.UPSTASH_REDIS_REST_URL,
    UPSTASH_REDIS_REST_TOKEN: process.env.UPSTASH_REDIS_REST_TOKEN,
    THERAPIST_SECRET_KEY: process.env.THERAPIST_SECRET_KEY,
    TERMS_VERSION: process.env.TERMS_VERSION,
    NODE_ENV: process.env.NODE_ENV,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_ANON_KEY: process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_CHATWOOT_WEBSITE_TOKEN: process.env.NEXT_PUBLIC_CHATWOOT_WEBSITE_TOKEN,
    NEXT_PUBLIC_CHATWOOT_BASE_URL: process.env.NEXT_PUBLIC_CHATWOOT_BASE_URL,
    NEXT_PUBLIC_VAPID_PUBLIC_KEY: process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY,
  },
  skipValidation: !!process.env.SKIP_ENV_VALIDATION,
  emptyStringAsUndefined: true,
});
