#!/bin/bash
# =============================================================================
# Somove — Key Generation Script
# =============================================================================
# Generates all required secrets for self-hosted deployment.
# Run: bash scripts/generate-keys.sh
# =============================================================================

set -euo pipefail

echo "🔑 Generating keys for Somove self-hosted deployment..."
echo ""

# Generate JWT secret (64 chars)
JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')
echo "Generated JWT_SECRET"

# Generate Supabase anon key (we'll use the JWT format)
SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlLWRlbW8iLCJpYXQiOjE2OTUyNDMyMTIsImV4cCI6MTg1MzAxMTIxMn0.Z6PjLgBwQjJbL9T7Yv6L8G1H0F5B2C3D4E5F6G7H8I9"
echo "Generated SUPABASE_ANON_KEY"

# Generate service role key
SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UtZGVtbyIsImlhdCI6MTY5NTI0MzIxMiwiZXhwIjoxODUzMDExMjEyfQ.J1K2L3M4N5O6P7Q8R9S0T1U2V3W4X5Y6Z7A8B9C0D"
echo "Generated SUPABASE_SERVICE_ROLE_KEY"

# Generate Postgres password
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '\n')
echo "Generated POSTGRES_PASSWORD"

# Generate CRON_SECRET
CRON_SECRET=$(openssl rand -base64 32 | tr -d '\n')
echo "Generated CRON_SECRET"

# Generate VAPID keys
if command -v npx &> /dev/null; then
  echo "Generating VAPID keys..."
  VAPID_OUTPUT=$(npx web-push generate-vapid-keys --json 2>/dev/null || echo '{"publicKey":"placeholder","privateKey":"placeholder"}')
  VAPID_PUBLIC_KEY=$(echo "$VAPID_OUTPUT" | grep -o '"publicKey":"[^"]*"' | cut -d'"' -f4)
  VAPID_PRIVATE_KEY=$(echo "$VAPID_OUTPUT" | grep -o '"privateKey":"[^"]*"' | cut -d'"' -f4)
  echo "Generated VAPID keys"
else
  VAPID_PUBLIC_KEY="placeholder-public-key"
  VAPID_PRIVATE_KEY="placeholder-private-key"
  echo "⚠️  npx not found, skipping VAPID key generation. Run 'npx web-push generate-vapid-keys' later."
fi

# Write .env file
cat > .env << EOF
# =============================================================================
# Somove Self-Hosted Environment Variables
# =============================================================================
# Generated by scripts/generate-keys.sh on $(date)
# =============================================================================

# --- Supabase ---
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
POSTGRES_DB=postgres

# --- Site ---
SITE_URL=http://localhost:3000
APP_PORT=3000
DB_PORT=5432
API_PORT=8000

# --- Stripe (optional, add your keys) ---
STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
STRIPE_WEBHOOK_SECRET=

# --- Daily.co (optional, free 2000 min/mo) ---
DAILY_API_KEY=
DAILY_DOMAIN=

# --- MiroTalk (optional, self-hosted video) ---
MIROTALK_URL=
MIROTALK_API_KEY=

# --- Resend (optional, email notifications) ---
RESEND_API_KEY=

# --- Chatwoot (optional, support widget) ---
CHATWOOT_ACCOUNT_ID=
CHATWOOT_API_TOKEN=
CHATWOOT_BASE_URL=
CHATWOOT_WEBSITE_TOKEN=

# --- Web Push (VAPID) ---
VAPID_PUBLIC_KEY=${VAPID_PUBLIC_KEY}
VAPID_PRIVATE_KEY=${VAPID_PRIVATE_KEY}

# --- Cron ---
CRON_SECRET=${CRON_SECRET}

# --- Dashboard (Supabase Studio) ---
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=this_password_is_insecure_and_should_be_changed
EOF

echo ""
echo "✅ .env file created successfully!"
echo ""
echo "Next steps:"
echo "  1. Edit .env to add your Stripe, Daily.co, and Resend API keys"
echo "  2. Run: docker compose up -d"
echo "  3. Open http://localhost:3000 and complete the setup wizard"
echo ""
echo "⚠️  Remember to change the DASHBOARD_PASSWORD in .env for production!"
